version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Downloads NSIS packager from our S3 bucket
      - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  -O $HOME/miniconda3.sh
      # Silently installs NSIS software for All Users on CodeBuild
      - bash $HOME/miniconda3.sh -b -p $HOME/miniconda
      # Display Python Version in build logs
      - python --version
      # Installs all required packages for Python and PyInstaller
      - pip install -U pyinstaller
      #- pip install-r requirements.txt
      - ~/miniconda3/bin/conda init bash
      - $HOME/miniconda env create -y --file environment.yml
      - $HOME/miniconda activate msblparser
    finally:
      - echo "End Install Phase" "Begin Pre-Build Phase"

  build:
    commands:
      # Run PyInstaller to build binaries
      - $HOME/miniconda activate msblparser
      - pyinstaller -y src/parseScoreboardCli.spec -distpath ./dist
      - echo "Finished PyInstaller creation"
    finally:
      - echo "End Build Phase" "Begin Post-Build Phase"

  post_build:
    commands:
      - echo "Finished build process"
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - '**/*'
  #discard-paths: yes
  base-directory: $Env:CODEBUILD_SRC_DIR/dist
#cache:
  #paths:
    # - paths